### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by sakmalh** [sepidsh/Housegan-data-reader#4]
```
Traceback (most recent call last):
  File "/home/akmal/APIIT/FYP Code/Housegan-data-reader/raster_to_json.py", line 294, in <module>
    raster_to_json(f"/home/akmal/APIIT/FYP Code/code_deep_layout/deep_layout/dataset/val/{x}.png")
  File "/home/akmal/APIIT/FYP Code/Housegan-data-reader/raster_to_json.py", line 264, in raster_to_json
    patch = PolygonPatch(polygon, facecolor=semantics_cmap["bedroom"], alpha=0.7)
  File "/home/akmal/APIIT/FYP Code/Housegan-data-reader/venv/lib/python3.10/site-packages/descartes/patch.py", line 87, in PolygonPatch
    return PathPatch(PolygonPath(polygon), **kwargs)
  File "/home/akmal/APIIT/FYP Code/Housegan-data-reader/venv/lib/python3.10/site-packages/descartes/patch.py", line 62, in PolygonPath
    vertices = concatenate([
  File "/home/akmal/APIIT/FYP Code/Housegan-data-reader/venv/lib/python3.10/site-packages/descartes/patch.py", line 63, in <listcomp>
    concatenate([asarray(t.exterior)[:, :2]] +
IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

Process finished with exit code 1
```

Is this the error mentioned in the other issues. Should I skip them?

**Comment by sepidsh** [comment]
no, the images that should skip get caught in asserts,  it seems you are doing something wrong. or at least that didnt happen for me .

**Comment by sakmalh** [comment]
At line 62 you should see this descartes/patch.py:
```
     vertices = concatenate([
     concatenate([asarray(t.exterior)[:, :2]] + [asarray(r)[:, :2] for r in t.interiors])
     for t in polygon])
```

Simply change t.exterior to t.exterior.coords. This hopefully should fix your issue.
```
    vertices = concatenate([
    concatenate([asarray(t.exterior.coords)[:, :2]] + [asarray(r)[:, :2] for r in t.interiors])
    for t in polygon])
```
Looks like because of version mismatch. This worked. Dropped it here for future
Thanks
